EnableImagePreviewing: false
InlineImagePreview: false
themes:
  - name: "monochromatic"
    colors:
    - "#FFFFFF"
    - "#FFFFFF"
    - "#F0F0F0"
    - "#E0E0E0"
    - "#D0D0D0"
    - "#C0C0C0"
    - "#B0B0B0"
    - "#A0A0A0"
    - "#909090"
    - "#808080"
    - "#707070"
    - "#606060"
    - "#505050"
    - "#404040"
    - "#303030"
    - "#202020"
    - "#101010"
    - "#000000"
    - "#000000"
    - "#000000"
    - "#000000"
    - "#000000"
    - "#000000"
    - "#000000"
    - "#000000"
    - "#000000"
